compile-interpreter: interpreter.pyj
	rapydscript interpreter.pyj -o ../static/quiz/js/rs-compiled/interpreter.js -p --screw-ie8

compile-toolbar: toolbar.pyj
	rapydscript toolbar.pyj -o ../static/quiz/js/rs-compiled/toolbar.js -p --screw-ie8

compile-find_url: find_url.pyj
	rapydscript find_url.pyj -o ../static/quiz/js/rs-compiled/find_url.js -p --screw-ie8