compile-interpreter: interpreter.pyj
	rapydscript interpreter.pyj -o ../static/quiz/js/interpreter.js -p --screw-ie8

compile-toolbar: toolbar.pyj
	rapydscript toolbar.pyj -o ../static/quiz/js/toolbar.js -p --screw-ie8

compile-find_url: find_url.pyj
	rapydscript find_url.pyj -o ../static/quiz/js/find_url.js -p --screw-ie8